export const ADD_CHAT = 'ADD_CHAT';
export const SET_CURRENT_COMPANION = 'SET_CURRENT_CHAT';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECIEVE_MESSAGE = 'RECIEVE_MESSAGE';

export const SET_USER_CREDENTIALS = 'SET_USER_CREDENTIALS';